[main]
bananen_version = "0.0.2-pre-alpha"

[config]
changelogfile = "CHANGELOG.MD"

[changes_md]
unreleased= """-  **<span style="color: #0033cc">Update</span>**: Every change type now has a color.
-  **fix**: `'dub'` no longer accepts empty releases.
"""
released= """## Testing out dub



## Test

-  **addition**: `'dub'` should now also basically work
-  **addition**: Basic functionality for `'add'`, `'init'` and `'regen'` was added.


"""