[main]
bananen_version = "0.0.1"

[config]
changelogfile = "CHANGELOG.MD"

[changes_md]
unreleased= """-  **addition**: Basic functionality for `'add'`, `'init'` and `'regen'` was added.
"""
released= """"""