[main]
bananen_version = "0.0.3-pre-alpha"

[config]
changelogfile = "CHANGELOG.MD"

[changes_md]
unreleased= """"""
released= """## 0.0.3-pre-alpha

-  **<span style="color: #0033cc">Update</span>**: Every change type now has a color.
-  **<span style="color: #9900cc">Fix</span>**: `'dub'` no longer accepts empty releases.
-  **<span style="color: #336600">Addition</span>**: `'dub'` should now also work basically.
-  **<span style="color: #336600">Addition</span>**: Basic functionality for `'add'`, `'init'` and `'regen'` was added.


"""