[package]
name = "bananen"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline_colorization = "0.1.5"
json = "0.12.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"