[package]
name = "bananen"
version = "0.0.2-pre-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inline_colorization = "0.1.5"
serde = { version = "1.0.104", features = ["derive"] }
toml = "0.7.6"
